### ISSUE TITLE
build fails even with dependencies

### ISSUE THREAD

**Issue by krob64** [nowrep/obs-vkcapture#214]
tried installing obs-vkcapture from AUR - doesn't compile
tried installing obs-vkcapture-git from AUR - doesn't compile
tried manually building from source - doesn't compile

they all fail at the same spot. 
[cmake_output.txt](https://github.com/user-attachments/files/15803250/cmake_output.txt)
[make_output.txt](https://github.com/user-attachments/files/15803257/make_output.txt)

also my LSP tells me it can't find obs-module.h but gcc obviously does find it, so why can't it resolve any of these obs symbols? really confuses me

**Comment by nowrep** [comment]
What is your OBS version? Support for OBS 27 was dropped recently.

**Comment by evilscientress** [comment]
I just stumbled over the same error and I figured out the problem. It's basically the same error as in #61. The fix 8a4dc7ff715588cb93d2e02e935744c8f4aeb3ab doesn't work. Though I have to admit that I don't know much about cmake and hence don't know how exactly the commit should have fixed the problem.

The problem is that cmake is trying to find libobs with the old deprecated `LibObs` package name. But the old cmake config files using that name have been removed in obsproject/obs-studio@106f5f9acea5e412f56e6a8b12f83bd78f3fb819.

What worked for me is to change `find_package(LibObs QUIET)` to `find_package(libobs REQUIRED)` in [CMakeLists.txt line 51](https://github.com/nowrep/obs-vkcapture/blob/eb4b07b75d13218877b16adc20ff8fdd28c02f5e/CMakeLists.txt#L51).
